# Generated by Django 5.2.17 on 2026-08-25 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0006_alter_patient_guardian_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='Age Group Label')),
                ('min_age_value', models.PositiveIntegerField(verbose_name='Min Age Value')),
                ('min_age_unit', models.CharField(choices=[('DAY', 'Day(s)'), ('MONTH', 'Month(s)'), ('YEAR', 'Year(s)')], default='YEAR', max_length=10, verbose_name='Min Age Unit')),
                ('max_age_value', models.PositiveIntegerField(verbose_name='Max Age Value')),
                ('max_age_unit', models.CharField(choices=[('DAY', 'Day(s)'), ('MONTH', 'Month(s)'), ('YEAR', 'Year(s)')], default='YEAR', max_length=10, verbose_name='Max Age Unit')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Diagnosis Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Diagnosis Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Investigation Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Investigation Code')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('sample_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sample Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Parameter Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Parameter Code')),
                ('default_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Default Unit')),
                ('data_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('TEXT', 'Text'), ('SELECT', 'Select/Dropdown')], default='NUMERIC', max_length=20, verbose_name='Data Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit Override')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lab.investigation')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='lab.parameter')),
            ],
            options={
                'ordering': ['investigation', 'display_order'],
                'unique_together': {('investigation', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='ParameterReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('ALL', 'All'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='ALL', max_length=10)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Min Value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Max Value')),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('critical_low', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Critical Low')),
                ('critical_high', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Critical High')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='lab.agegroup')),
                ('diagnosis', models.ForeignKey(blank=True, help_text='Null means generic range for this age group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='lab.diagnosis')),
                ('investigation_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='lab.investigationparameter')),
            ],
            options={
                'unique_together': {('investigation_parameter', 'age_group', 'diagnosis', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='PatientInvestigationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='lab.diagnosis')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='lab.investigation')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders_placed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient')),
            ],
            options={
                'ordering': ['-ordered_on'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisInvestigationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default for Diagnosis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_maps', to='lab.diagnosis')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_maps', to='lab.investigation')),
            ],
            options={
                'ordering': ['diagnosis', 'investigation'],
                'unique_together': {('diagnosis', 'investigation')},
            },
        ),
        migrations.CreateModel(
            name='PatientInvestigationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_value', models.CharField(max_length=255, verbose_name='Result Value')),
                ('flag', models.CharField(choices=[('NORMAL', 'Normal'), ('ABNORMAL_LOW', 'Abnormal Low'), ('ABNORMAL_HIGH', 'Abnormal High'), ('CRITICAL_LOW', 'Critical Low'), ('CRITICAL_HIGH', 'Critical High'), ('NOT_CONFIGURED', 'Not Configured')], default='NORMAL', max_length=20)),
                ('entered_on', models.DateTimeField(auto_now=True)),
                ('applied_reference_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_results', to='lab.parameterreferencerange')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_entered', to=settings.AUTH_USER_MODEL)),
                ('investigation_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.investigationparameter')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.patientinvestigationorder')),
            ],
            options={
                'unique_together': {('order', 'investigation_parameter')},
            },
        ),
    ]
