# Generated by Django 5.2.17 on 2026-08-25 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Sample Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='investigation',
            name='is_panel',
            field=models.BooleanField(default=False, verbose_name='Is Panel (Multi-parameter)'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name / Alias'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='turnaround_time_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Turnaround Time (Hours)'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to='lab.labdepartment', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='sample_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to='lab.sampletype', verbose_name='Sample Type'),
        ),
    ]
