# Generated by Django 5.2.17 on 2026-08-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_labdepartment_sampletype_investigation_is_panel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Complaint Name')),
                ('legacy_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Legacy Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code (Legacy Accession)')),
                ('category', models.CharField(choices=[('Bed Charge', 'Bed Charge'), ('Ambulance', 'Ambulance'), ('OT Charge', 'OT Charge'), ('Dialysis', 'Dialysis'), ('Physiotherapy Modality', 'Physiotherapy Modality'), ('Other', 'Other')], default='Other', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StagingDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(max_length=50, unique=True)),
                ('legacy_text', models.CharField(max_length=255)),
                ('migrated', models.BooleanField(default=False)),
                ('migrated_to_type', models.CharField(blank=True, help_text='Diagnosis, ChiefComplaint, or Skipped', max_length=50, null=True)),
                ('migrated_to_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['legacy_id'],
            },
        ),
        migrations.CreateModel(
            name='StagingInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_code', models.CharField(max_length=50, unique=True)),
                ('legacy_text', models.CharField(max_length=255)),
                ('migrated', models.BooleanField(default=False)),
                ('migrated_to_type', models.CharField(blank=True, help_text='Investigation, HospitalService, or Skipped', max_length=50, null=True)),
                ('migrated_to_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['legacy_code'],
            },
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='chapter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chapter'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='icd11_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ICD-11 Title'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='legacy_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Legacy Code'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='synonyms',
            field=models.TextField(blank=True, null=True, verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='legacy_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Legacy Code'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='ICD-11 Code'),
        ),
    ]
