# Generated by Django 5.2.17 on 2026-08-25 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_chiefcomplaint_hospitalservice_stagingdiagnosis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='icd_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ICD Version'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Source (e.g. WHO, Import)'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='who_uri',
            field=models.URLField(blank=True, null=True, verbose_name='WHO URI'),
        ),
        migrations.CreateModel(
            name='DiagnosisImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('duplicates', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
