# Generated by Django 5.2.17 on 2026-08-25 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_diagnosis_icd_version_diagnosis_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investigationparameter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='child_reference_range',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Child Reference Range'),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parameter Code'),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='critical_high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Critical High'),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='critical_low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Critical Low'),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='decimal_precision',
            field=models.IntegerField(blank=True, null=True, verbose_name='Decimal Precision'),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='female_reference_range',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Female Reference Range'),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='male_reference_range',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Male Reference Range'),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='maximum_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Age'),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='minimum_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Age'),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Parameter Name'),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='reference_range',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference Range'),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='result_type',
            field=models.CharField(default='Numeric', max_length=50, verbose_name='Result Type'),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='investigationparameter',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='lab.parameter'),
        ),
        migrations.AlterField(
            model_name='investigationparameter',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
        migrations.AlterUniqueTogether(
            name='investigationparameter',
            unique_together={('investigation', 'code')},
        ),
        migrations.CreateModel(
            name='InvestigationImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('total_investigations', models.IntegerField(default=0)),
                ('total_parameters', models.IntegerField(default=0)),
                ('investigations_imported', models.IntegerField(default=0)),
                ('investigations_updated', models.IntegerField(default=0)),
                ('investigations_skipped', models.IntegerField(default=0)),
                ('parameters_imported', models.IntegerField(default=0)),
                ('parameters_updated', models.IntegerField(default=0)),
                ('parameters_skipped', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
