# Generated by Django 5.2.17 on 2026-08-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_alter_investigationparameter_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='code',
            field=models.CharField(default='DEFAULT', max_length=50, unique=True, verbose_name='Age Group Code'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='gender',
            field=models.CharField(choices=[('All', 'All'), ('Male', 'Male'), ('Female', 'Female')], default='All', max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='pregnancy_applicable',
            field=models.BooleanField(default=False, verbose_name='Pregnancy Applicable'),
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='interpretation',
            field=models.TextField(blank=True, null=True, verbose_name='Interpretation'),
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='reference_text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reference Text'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Age Group Name'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='max_age_unit',
            field=models.CharField(choices=[('Days', 'Days'), ('Months', 'Months'), ('Years', 'Years')], default='Years', max_length=10, verbose_name='Max Age Unit'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='min_age_unit',
            field=models.CharField(choices=[('Days', 'Days'), ('Months', 'Months'), ('Years', 'Years')], default='Years', max_length=10, verbose_name='Min Age Unit'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='parameterreferencerange',
            name='gender',
            field=models.CharField(choices=[('All', 'All'), ('Male', 'Male'), ('Female', 'Female')], default='All', max_length=10),
        ),
    ]
