# Generated by Django 5.2.17 on 2026-08-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_agegroupimporthistory_parameterimporthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='max_age_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Age Value'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='min_age_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Min Age Value'),
        ),
    ]
