# Generated by Django 5.2.17 on 2026-08-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_alter_agegroup_max_age_value_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameterreferencerange',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='pregnancy',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('N/A', 'N/A')], default='No', max_length=10, verbose_name='Pregnancy'),
        ),
        migrations.AlterUniqueTogether(
            name='parameterreferencerange',
            unique_together={('investigation_parameter', 'age_group', 'gender', 'pregnancy')},
        ),
    ]
