# Generated by Django 5.2.17 on 2026-08-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_alter_parameterreferencerange_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterreferencerange',
            name='method',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='range_type',
            field=models.CharField(choices=[('Numeric', 'Numeric Range'), ('Text', 'Text / Qualitative'), ('None', 'No Reference Range')], default='Numeric', max_length=20, verbose_name='Range Type'),
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
