# Generated by Django 5.2.17 on 2026-08-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_referencerangeimporthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencerangeimporthistory',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='referencerange_imports/'),
        ),
    ]
