# Generated by Django 5.2.17 on 2026-08-27 06:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_referencerangeimporthistory_upload_file'),
        ('patients', '0010_patientimporthistory_upload_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_type', models.CharField(choices=[('OP', 'OP'), ('INPATIENT', 'Inpatient')], default='OP', max_length=20)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('sample_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Saved', 'Saved'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests_consulted', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_requests', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='lab.labdepartment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('chief_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.chiefcomplaint')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.diagnosis')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='lab.servicerequest')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('AUTO_SUGGESTED', 'Auto Suggested'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('is_removed', models.BooleanField(default=False)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.investigation')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='lab.servicerequest')),
            ],
        ),
    ]
