# Generated by Django 5.2.17 on 2026-08-27 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_servicerequest_servicerequestdiagnosis_and_more'),
        ('patients', '0010_patientimporthistory_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisitDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chief_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.chiefcomplaint')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.diagnosis')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patientvisit')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('visit', 'chief_complaint'), ('visit', 'diagnosis')},
            },
        ),
    ]
