# Generated by Django 5.2.17 on 2026-08-27 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_patientvisitdiagnosis'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diagnosisinvestigationmap',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='diagnosisinvestigationmap',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_maps', to='lab.agegroup', verbose_name='Specific Age Group'),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosisinvestigationmap',
            unique_together={('diagnosis', 'investigation', 'age_group')},
        ),
    ]
