# Generated by Django 5.2.17 on 2026-08-27 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_alter_diagnosisinvestigationmap_unique_together_and_more'),
        ('patients', '0010_patientimporthistory_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='patients.department'),
        ),
    ]
