# Generated by Django 5.2.17 on 2026-08-27 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_alter_servicerequest_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestinvestigation',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequestinvestigation',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequestinvestigation',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequestinvestigation',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequestinvestigation',
            name='received_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequestinvestigation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceRequestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_value', models.CharField(max_length=255, verbose_name='Result Value')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('applied_reference_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.parameterreferencerange')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('investigation_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.investigationparameter')),
                ('sr_investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.servicerequestinvestigation')),
            ],
            options={
                'unique_together': {('sr_investigation', 'investigation_parameter')},
            },
        ),
    ]
