# Generated by Django 5.2.17 on 2026-08-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_migrate_legacy_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Consultant Name'),
        ),
    ]
