# Generated by Django 5.2.17 on 2026-08-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0019_servicerequest_consultant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='visit_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Visit No'),
        ),
    ]
