# Generated by Django 5.2.17 on 2026-08-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0020_servicerequest_visit_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisinvestigationmap',
            name='mapping_type',
            field=models.CharField(choices=[('RECOMMEND', 'Recommend (Auto Select)'), ('OPTIONAL', 'Optional (User Can Choose)'), ('NOT_RECOMMENDED', 'Not Recommended (Do Not Show)')], default='RECOMMEND', max_length=20, verbose_name='Mapping Type'),
        ),
    ]
