# Generated by Django 5.2.17 on 2026-08-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0021_diagnosisinvestigationmap_mapping_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiagnosisInvestigationMap',
        ),
    ]
