# Generated by Django 5.2.17 on 2026-08-28 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0022_delete_diagnosisinvestigationmap'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameterreferencerange',
            unique_together={('investigation_parameter', 'age_group', 'diagnosis', 'gender')},
        ),
    ]
