# Generated by Django 5.2.17 on 2026-08-28 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0023_alter_parameterreferencerange_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisInvestigationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Investigation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_mappings', to='lab.diagnosis')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.investigation')),
            ],
            options={
                'ordering': ['diagnosis', 'investigation'],
                'unique_together': {('diagnosis', 'investigation')},
            },
        ),
    ]
