# Generated by Django 5.2.17 on 2026-08-28 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0024_diagnosisinvestigationmap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosisinvestigationmap',
            options={'ordering': ['diagnosis', 'age_group', 'investigation']},
        ),
        migrations.AlterUniqueTogether(
            name='diagnosisinvestigationmap',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='diagnosisinvestigationmap',
            name='age_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_mappings', to='lab.agegroup'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='diagnosisinvestigationmap',
            unique_together={('diagnosis', 'age_group', 'investigation')},
        ),
    ]
