# Generated by Django 5.2.17 on 2026-08-28 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0025_alter_diagnosisinvestigationmap_options_and_more'),
        ('patients', '0010_patientimporthistory_upload_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTriggerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_entries', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutoTriggerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('requested_entries', models.PositiveIntegerField()),
                ('processed_entries', models.PositiveIntegerField(default=0)),
                ('successful', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Partially Completed', 'Partially Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Queued', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.autotriggerconfig')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.department')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutoTriggerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_no', models.PositiveIntegerField()),
                ('entry_date', models.DateField()),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Skipped', 'Skipped')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='lab.autotriggerhistory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
