# Generated by Django 5.2.17 on 2026-08-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0026_autotriggerconfig_autotriggerhistory_autotriggerlog'),
        ('patients', '0010_patientimporthistory_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotriggerhistory',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autotriggerhistory',
            name='remaining_entries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autotriggerhistory',
            name='rush_entries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autotriggerhistory',
            name='rush_percentage',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.CreateModel(
            name='AutoTriggerTimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Schedule', max_length=150)),
                ('lab_day_start', models.TimeField(default='16:00:00')),
                ('lab_day_end', models.TimeField(default='15:59:00')),
                ('rush_start', models.TimeField(default='10:00:00')),
                ('rush_end', models.TimeField(default='14:00:00')),
                ('rush_percentage', models.PositiveIntegerField(default=75)),
                ('processing_interval', models.PositiveIntegerField(default=30, help_text='In minutes')),
                ('is_active', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, help_text='Optional department specific setting', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='autotriggerconfig',
            name='time_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.autotriggertimesetting'),
        ),
    ]
