# Generated by Django 5.2.17 on 2026-08-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0027_autotriggerhistory_last_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotriggerhistory',
            name='schedule_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
