# Generated by Django 5.2.17 on 2026-08-28 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0028_autotriggerhistory_schedule_data'),
        ('patients', '0010_patientimporthistory_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotriggerlog',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patientvisit'),
        ),
    ]
