# Generated by Django 5.2.17 on 2026-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0029_autotriggerlog_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autotriggerconfig',
            name='total_entries',
        ),
        migrations.RemoveField(
            model_name='autotriggerhistory',
            name='requested_entries',
        ),
        migrations.AddField(
            model_name='autotriggerconfig',
            name='day_end_time',
            field=models.TimeField(default='03:59:00'),
        ),
        migrations.AddField(
            model_name='autotriggerconfig',
            name='day_start_time',
            field=models.TimeField(default='04:00:00'),
        ),
        migrations.AddField(
            model_name='autotriggerconfig',
            name='max_entries',
            field=models.PositiveIntegerField(default=125),
        ),
        migrations.AddField(
            model_name='autotriggerconfig',
            name='min_entries',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='autotriggerconfig',
            name='trigger_start_time',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AddField(
            model_name='autotriggerhistory',
            name='day_end_time',
            field=models.TimeField(default='03:59:00'),
        ),
        migrations.AddField(
            model_name='autotriggerhistory',
            name='day_start_time',
            field=models.TimeField(default='04:00:00'),
        ),
        migrations.AddField(
            model_name='autotriggerhistory',
            name='max_entries',
            field=models.PositiveIntegerField(default=125),
        ),
        migrations.AddField(
            model_name='autotriggerhistory',
            name='min_entries',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='autotriggerhistory',
            name='trigger_start_time',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AlterField(
            model_name='autotriggertimesetting',
            name='lab_day_end',
            field=models.TimeField(default='03:59:00'),
        ),
        migrations.AlterField(
            model_name='autotriggertimesetting',
            name='lab_day_start',
            field=models.TimeField(default='04:00:00'),
        ),
    ]
