# Generated by Django 5.2.17 on 2026-08-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0030_remove_autotriggerconfig_total_entries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotriggerconfig',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
