# Generated by Django 5.2.17 on 2026-08-28 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0031_autotriggerconfig_description'),
        ('patients', '0010_patientimporthistory_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotriggerlog',
            name='new_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trigger_logs', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='autotriggerlog',
            name='source_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_trigger_logs', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='autotriggerlog',
            name='stage',
            field=models.CharField(default='STAGE 1 — PATIENT CREATION', max_length=50),
        ),
    ]
