# Generated by Django 5.2.17 on 2026-08-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0032_autotriggerlog_new_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotriggertimesetting',
            name='processing_interval',
            field=models.FloatField(default=30.0, help_text='In minutes (e.g. 0.5 for 30 seconds)'),
        ),
    ]
