# Generated by Django 5.2.17 on 2026-08-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0033_alter_autotriggertimesetting_processing_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotriggerlog',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
