# Generated by Django 5.2.17 on 2026-08-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0034_autotriggerlog_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotriggerhistory',
            name='current_stage',
            field=models.CharField(default='STAGE 1 — PATIENT CREATION', max_length=100),
        ),
        migrations.AddField(
            model_name='autotriggerhistory',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
