# Generated by Django 5.2.17 on 2026-08-30 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0035_autotriggerhistory_current_stage_and_more'),
        ('patients', '0012_patient_patient_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisDepartmentMappingImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='mapping_imports/')),
                ('total_records', models.IntegerField(default=0)),
                ('imported', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisDepartmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_mappings', to='patients.department')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_mappings', to='lab.diagnosis')),
            ],
            options={
                'ordering': ['department__name', 'diagnosis__name'],
                'constraints': [models.UniqueConstraint(fields=('department', 'diagnosis'), name='unique_department_diagnosis_mapping')],
            },
        ),
    ]
