# Generated by Django 5.2.17 on 2026-08-31 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0036_diagnosisdepartmentmappingimporthistory_and_more'),
        ('patients', '0012_patient_patient_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTriggerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('source_from_date', models.DateField()),
                ('source_to_date', models.DateField()),
                ('trigger_start_time', models.TimeField(default='08:00:00')),
                ('trigger_stop_time', models.TimeField(default='13:59:00')),
                ('interval_mins', models.FloatField(default=1.5)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('is_saved', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.department')),
            ],
            options={
                'unique_together': {('department', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyTriggerDailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_date', models.DateField()),
                ('min_entries', models.PositiveIntegerField(default=0)),
                ('max_entries', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to='lab.monthlytriggerplan')),
            ],
            options={
                'ordering': ['target_date'],
                'unique_together': {('plan', 'target_date')},
            },
        ),
    ]
