# Generated by Django 5.2.17 on 2026-08-31 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0037_monthlytriggerplan_monthlytriggerdailytarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytriggerdailytarget',
            name='created_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlytriggerdailytarget',
            name='duplicates_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlytriggerdailytarget',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytriggerdailytarget',
            name='status',
            field=models.CharField(default='Not Started', max_length=50),
        ),
        migrations.CreateModel(
            name='MonthlyTriggerExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('duplicates_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='lab.monthlytriggerplan')),
                ('stopped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
