# Generated by Django 5.2.17 on 2026-08-31 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0038_monthlytriggerdailytarget_created_count_and_more'),
        ('patients', '0012_patient_patient_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlytriggerplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='monthlytriggerdailytarget',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='monthlytriggerplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monthlytriggerdailytarget',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlytriggerplan',
            name='automation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytriggerplan',
            name='automation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytriggerplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlytriggerdailytarget',
            name='max_entries',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='monthlytriggerdailytarget',
            name='min_entries',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterUniqueTogether(
            name='monthlytriggerdailytarget',
            unique_together={('plan', 'department', 'target_date')},
        ),
        migrations.RemoveField(
            model_name='monthlytriggerplan',
            name='department',
        ),
        migrations.RemoveField(
            model_name='monthlytriggerplan',
            name='month',
        ),
        migrations.RemoveField(
            model_name='monthlytriggerplan',
            name='year',
        ),
    ]
