# Generated by Django 5.2.17 on 2026-08-31 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0039_alter_monthlytriggerplan_options_and_more'),
        ('patients', '0012_patient_patient_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTriggerGeneratedPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_trigger_records', to='patients.patient')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_patients', to='lab.monthlytriggerdailytarget')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
