# Generated by Django 5.2.17 on 2026-08-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0040_monthlytriggergeneratedpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytriggerdailytarget',
            name='new_op_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlytriggerdailytarget',
            name='new_op_target',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='monthlytriggerdailytarget',
            name='review_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlytriggerdailytarget',
            name='review_target',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='monthlytriggerexecutionlog',
            name='new_op_created_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlytriggerexecutionlog',
            name='review_completed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlytriggerplan',
            name='review_source_month_year',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
