# Generated by Django 5.2.17 on 2026-08-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0041_monthlytriggerdailytarget_new_op_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytriggergeneratedpatient',
            name='op_type',
            field=models.CharField(default='NEW OP', max_length=20),
        ),
    ]
