# Generated by Django 5.2.17 on 2026-09-01 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0042_monthlytriggergeneratedpatient_op_type'),
        ('patients', '0013_alter_patient_visit_through_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='diagnosisdepartmentmapping',
            name='unique_department_diagnosis_mapping',
        ),
        migrations.AddField(
            model_name='diagnosisdepartmentmapping',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_diagnosis_mappings', to='lab.agegroup'),
        ),
        migrations.AddField(
            model_name='monthlytriggergeneratedpatient',
            name='age_group_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlytriggergeneratedpatient',
            name='diagnosis_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='diagnosisdepartmentmapping',
            constraint=models.UniqueConstraint(fields=('department', 'diagnosis', 'age_group'), name='unique_department_diagnosis_mapping'),
        ),
    ]
