# Generated by Django 5.2.17 on 2026-09-01 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0043_remove_diagnosisdepartmentmapping_unique_department_diagnosis_mapping_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationDummyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_id', models.CharField(max_length=50, unique=True)),
                ('investigation_code', models.CharField(blank=True, max_length=50)),
                ('dummy_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Saved', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_automation_test', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dummy_results', to='lab.investigation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationDummyResultParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter_name', models.CharField(max_length=255)),
                ('result_value', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('dummy_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lab.automationdummyresult')),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dummy_results', to='lab.parameter')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
