# Generated by Django 5.2.17 on 2026-09-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0044_automationdummyresult_automationdummyresultparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Diagnosis Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='ICD-11 Code')),
                ('icd11_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='ICD-11 Title')),
                ('chapter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chapter')),
                ('synonyms', models.TextField(blank=True, null=True, verbose_name='Synonyms')),
                ('legacy_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Legacy Code')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Source (e.g. WHO, Import)')),
                ('icd_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='ICD Version')),
                ('who_uri', models.URLField(blank=True, null=True, verbose_name='WHO URI')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['name'],
            },
        ),
    ]
