# Generated by Django 5.2.17 on 2026-09-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0045_labdiagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='class_kind',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Class Kind'),
        ),
        migrations.AddField(
            model_name='labdiagnosis',
            name='class_kind',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Class Kind'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ICD-11 Code'),
        ),
        migrations.AlterField(
            model_name='labdiagnosis',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ICD-11 Code'),
        ),
    ]
