# Generated by Django 5.2.17 on 2026-09-08 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0046_diagnosis_class_kind_labdiagnosis_class_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterreferencerange',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='lab.agegroup'),
        ),
    ]
