# Generated by Django 5.2.17 on 2026-09-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0047_alter_parameterreferencerange_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisinvestigationmap',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_mappings', to='lab.agegroup'),
        ),
    ]
