# Generated by Django 5.2.17 on 2026-09-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0048_alter_diagnosisinvestigationmap_age_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationdummyresult',
            name='patient_age_display',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='automationdummyresult',
            name='patient_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationdummyresult',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='automationdummyresult',
            name='patient_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
