# Generated by Django 5.2.17 on 2026-09-11 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0050_add_result_status_and_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='labdepartment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='lab.labdepartment', verbose_name='Parent Department'),
        ),
    ]
