# Generated by Django 5.2.17 on 2026-09-11 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0051_labdepartment_parent'),
        ('patients', '0013_alter_patient_visit_through_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmappedLabInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_department_name', models.CharField(max_length=255)),
                ('source_category', models.CharField(blank=True, max_length=255, null=True)),
                ('investigation_name', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='labdepartment',
            name='parent',
        ),
        migrations.AddField(
            model_name='servicerequestinvestigation',
            name='result_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Overall Result Status'),
        ),
        migrations.AddField(
            model_name='servicerequestresult',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Parameter Result Status'),
        ),
        migrations.CreateModel(
            name='LabWorkloadMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_benchmark', models.PositiveIntegerField(blank=True, null=True)),
                ('weekly_benchmark', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_benchmark', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_workloads', to='patients.department')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='lab.investigation')),
                ('lab_sub_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='lab.labdepartment')),
            ],
            options={
                'ordering': ['hospital_department', 'lab_sub_department', 'investigation'],
                'unique_together': {('hospital_department', 'lab_sub_department', 'investigation')},
            },
        ),
    ]
