# Generated by Django 5.2.17 on 2026-09-20 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0052_unmappedlabinvestigation_remove_labdepartment_parent_and_more'),
        ('patients', '0016_alter_patient_mobile_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATCSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default ATC Settings', max_length=100)),
                ('default_start_time', models.TimeField(default='08:00:00', verbose_name='Default Start Time')),
                ('default_end_time', models.TimeField(default='14:00:00', verbose_name='Default End Time')),
                ('max_future_days', models.PositiveIntegerField(default=30, verbose_name='Max Future Generation Period (Days)')),
                ('op_date_restriction', models.BooleanField(default=True, verbose_name='Enforce OP Today Only Restriction')),
                ('allow_review_backdated', models.BooleanField(default=True, verbose_name='Allow Backdated Review Dates')),
                ('allow_review_future', models.BooleanField(default=True, verbose_name='Allow Future Review Dates')),
                ('default_batch_size', models.PositiveIntegerField(default=100, verbose_name='Default Batch Size')),
                ('allowed_modes', models.JSONField(blank=True, default=list, verbose_name='Allowed Automation Modes')),
                ('source_from_year', models.PositiveIntegerField(default=2022, verbose_name='Default Source From Year')),
                ('source_to_year', models.PositiveIntegerField(default=2024, verbose_name='Default Source To Year')),
                ('gender_ratio_male_pct', models.PositiveIntegerField(default=60, verbose_name='Default Male %')),
                ('gender_ratio_female_pct', models.PositiveIntegerField(default=40, verbose_name='Default Female %')),
                ('emergency_stop_policy', models.CharField(default='IMMEDIATE_PRESERVE', max_length=50, verbose_name='Emergency Stop Policy')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ATC Setting',
                'verbose_name_plural': 'ATC Settings',
            },
        ),
        migrations.CreateModel(
            name='ATCJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('mode', models.CharField(choices=[('OP', 'OP'), ('REVIEW', 'Review'), ('FUTURE_PATIENT', 'Future Patient')], default='OP', max_length=20)),
                ('source_from_year', models.PositiveIntegerField(default=2022)),
                ('source_to_year', models.PositiveIntegerField(default=2024)),
                ('target_total', models.PositiveIntegerField(default=0)),
                ('target_male', models.PositiveIntegerField(default=0)),
                ('target_female', models.PositiveIntegerField(default=0)),
                ('schedule_start_time', models.TimeField(default='08:00:00')),
                ('schedule_end_time', models.TimeField(default='14:00:00')),
                ('batch_size', models.PositiveIntegerField(default=100)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IDLE', 'IDLE'), ('STARTING', 'STARTING'), ('RUNNING', 'RUNNING'), ('STOP_REQUESTED', 'STOP_REQUESTED'), ('STOPPED', 'STOPPED'), ('EMERGENCY_STOPPED', 'EMERGENCY STOPPED'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='IDLE', max_length=30)),
                ('current_batch', models.PositiveIntegerField(default=0)),
                ('total_batches', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('created_male', models.PositiveIntegerField(default=0)),
                ('created_female', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('current_patient_info', models.CharField(blank=True, default='', max_length=255)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('stop_reason', models.CharField(blank=True, default='', max_length=255)),
                ('stop_requested', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ATCJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_name', models.CharField(blank=True, default='', max_length=150)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('batch_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Skipped', 'Skipped')], default='Success', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='lab.atcjob')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atc_logs', to='patients.patient')),
                ('source_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atc_logs', to='patients.patientvisit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
