# Generated by Django 5.2.17 on 2026-09-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0053_atcsetting_atcjob_atcjoblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcjob',
            name='created_op',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='created_review',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='op_daily_pct',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='review_pct',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='review_source_year',
            field=models.PositiveIntegerField(blank=True, default=2024, null=True),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='target_op',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='target_review',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atcsetting',
            name='default_op_daily_pct',
            field=models.PositiveIntegerField(default=75, verbose_name='Default OP Daily %'),
        ),
        migrations.AddField(
            model_name='atcsetting',
            name='default_review_pct',
            field=models.PositiveIntegerField(default=25, verbose_name='Default Review %'),
        ),
        migrations.AddField(
            model_name='atcsetting',
            name='default_review_source_year',
            field=models.PositiveIntegerField(default=2024, verbose_name='Default Review Source Year'),
        ),
        migrations.AlterField(
            model_name='atcjob',
            name='mode',
            field=models.CharField(choices=[('OP', 'OP'), ('REVIEW', 'Review'), ('COMBINED', 'Combined OP + Review')], default='COMBINED', max_length=20),
        ),
    ]
