# Generated by Django 5.2.17 on 2026-09-20 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0054_atcjob_created_op_atcjob_created_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atcjob',
            name='op_date_mode',
            field=models.CharField(blank=True, default='1_DAY', max_length=20),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='op_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='op_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='review_date_mode',
            field=models.CharField(blank=True, default='1_DAY', max_length=20),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='review_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='review_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atc_jobs_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atcjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atc_jobs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atcjob',
            name='mode',
            field=models.CharField(choices=[('OP', 'OP'), ('REVIEW', 'Review'), ('ALL', 'All (OP + Review)'), ('COMBINED', 'Combined OP + Review'), ('FUTURE_PATIENT', 'Future Patient')], default='COMBINED', max_length=20),
        ),
        migrations.AlterField(
            model_name='atcjob',
            name='status',
            field=models.CharField(choices=[('IDLE', 'IDLE'), ('DRAFT', 'DRAFT'), ('SAVED', 'SAVED'), ('STARTING', 'STARTING'), ('RUNNING', 'RUNNING'), ('STOP_REQUESTED', 'STOP_REQUESTED'), ('STOPPED', 'STOPPED'), ('EMERGENCY_STOPPED', 'EMERGENCY STOPPED'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='IDLE', max_length=30),
        ),
    ]
