# Generated by Django 5.2.17 on 2026-09-20 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0055_atcjob_op_date_mode_atcjob_op_from_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atcjob',
            name='op_date_mode',
        ),
        migrations.RemoveField(
            model_name='atcjob',
            name='op_from_date',
        ),
        migrations.RemoveField(
            model_name='atcjob',
            name='op_to_date',
        ),
        migrations.RemoveField(
            model_name='atcjob',
            name='review_date_mode',
        ),
        migrations.RemoveField(
            model_name='atcjob',
            name='review_from_date',
        ),
        migrations.RemoveField(
            model_name='atcjob',
            name='review_to_date',
        ),
        migrations.RemoveField(
            model_name='atcjob',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='atcjob',
            name='date_mode',
            field=models.CharField(choices=[('ALL', 'All'), ('BACKDATE', 'Backdate'), ('FRONTDATE', 'Frontdate')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='source_year',
            field=models.CharField(blank=True, default='2024', max_length=20),
        ),
        migrations.AddField(
            model_name='atcsetting',
            name='default_date_mode',
            field=models.CharField(default='ALL', max_length=20, verbose_name='Default Date Mode'),
        ),
        migrations.AddField(
            model_name='atcsetting',
            name='default_source_year',
            field=models.CharField(blank=True, default='2024', max_length=20, verbose_name='Default Source Year'),
        ),
        migrations.AlterField(
            model_name='atcjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atcjob',
            name='mode',
            field=models.CharField(choices=[('OP', 'OP'), ('REVIEW', 'Review'), ('COMBINED', 'Combined OP + Review'), ('FUTURE_PATIENT', 'Future Patient')], default='COMBINED', max_length=20),
        ),
        migrations.AlterField(
            model_name='atcjob',
            name='status',
            field=models.CharField(choices=[('IDLE', 'IDLE'), ('STARTING', 'STARTING'), ('RUNNING', 'RUNNING'), ('STOP_REQUESTED', 'STOP_REQUESTED'), ('STOPPED', 'STOPPED'), ('EMERGENCY_STOPPED', 'EMERGENCY STOPPED'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='IDLE', max_length=30),
        ),
    ]
