# Generated by Django 5.2.17 on 2026-09-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0056_remove_atcjob_op_date_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atcjob',
            name='date_mode',
        ),
        migrations.RemoveField(
            model_name='atcjob',
            name='source_year',
        ),
        migrations.RemoveField(
            model_name='atcsetting',
            name='default_date_mode',
        ),
        migrations.RemoveField(
            model_name='atcsetting',
            name='default_source_year',
        ),
        migrations.AddField(
            model_name='atcjob',
            name='child_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='daily_targets',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='operation_signal',
            field=models.CharField(default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='plan_departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='source_data_period',
            field=models.CharField(default='2024 – 2025', max_length=50),
        ),
        migrations.AlterField(
            model_name='atcjob',
            name='status',
            field=models.CharField(choices=[('IDLE', 'IDLE'), ('DRAFT', 'DRAFT'), ('STARTING', 'STARTING'), ('RUNNING', 'RUNNING'), ('STOP_REQUESTED', 'STOP_REQUESTED'), ('STOPPED', 'STOPPED'), ('EMERGENCY_STOPPED', 'EMERGENCY STOPPED'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='IDLE', max_length=30),
        ),
    ]
