# Generated by Django 5.2.17 on 2026-09-21 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0057_remove_atcjob_date_mode_remove_atcjob_source_year_and_more'),
        ('patients', '0017_ward_alter_patient_guardian_relationship_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atcjob',
            name='automation_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_jobs', to='lab.atcjob'),
        ),
        migrations.AddField(
            model_name='atcjob',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atcjob',
            name='status',
            field=models.CharField(choices=[('IDLE', 'IDLE'), ('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('READY', 'READY'), ('STARTING', 'STARTING'), ('RUNNING', 'RUNNING'), ('STOP_REQUESTED', 'STOP_REQUESTED'), ('STOPPED', 'STOPPED'), ('EMERGENCY_STOPPED', 'EMERGENCY STOPPED'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='IDLE', max_length=30),
        ),
        migrations.AddIndex(
            model_name='atcjob',
            index=models.Index(fields=['automation_date', 'status'], name='lab_atcjob_automat_636702_idx'),
        ),
        migrations.AddIndex(
            model_name='atcjob',
            index=models.Index(fields=['plan', 'automation_date'], name='lab_atcjob_plan_id_1a4c4d_idx'),
        ),
    ]
