# Generated by Django 5.2.17 on 2026-09-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0058_atcjob_automation_date_atcjob_plan_atcjob_stopped_at_and_more'),
        ('patients', '0017_ward_alter_patient_guardian_relationship_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosisinvestigationmap',
            options={'ordering': ['priority', 'diagnosis', 'investigation']},
        ),
        migrations.AlterModelOptions(
            name='investigation',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_diagnoses', to='patients.department'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='gender_eligibility',
            field=models.CharField(choices=[('All', 'All'), ('Male', 'Male'), ('Female', 'Female')], default='All', max_length=10, verbose_name='Gender Eligibility'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Age'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Age'),
        ),
        migrations.AddField(
            model_name='diagnosisinvestigationmap',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_investigation_mappings', to='patients.department'),
        ),
        migrations.AddField(
            model_name='diagnosisinvestigationmap',
            name='gender',
            field=models.CharField(choices=[('All', 'All'), ('Male', 'Male'), ('Female', 'Female')], default='All', max_length=10),
        ),
        migrations.AddField(
            model_name='diagnosisinvestigationmap',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisinvestigationmap',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisinvestigationmap',
            name='pregnancy_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosisinvestigationmap',
            name='priority',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='investigation',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='method',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='specimen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Specimen'),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='is_calculated',
            field=models.BooleanField(default=False, verbose_name='Is Calculated'),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='is_mandatory',
            field=models.BooleanField(default=False, verbose_name='Is Mandatory'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='default_decimal_places',
            field=models.PositiveIntegerField(blank=True, default=2, null=True, verbose_name='Default Decimal Places'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='result_type',
            field=models.CharField(blank=True, default='Numeric', max_length=50, null=True, verbose_name='Result Type'),
        ),
        migrations.CreateModel(
            name='DiagnosisEligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('All', 'All'), ('Male', 'Male'), ('Female', 'Female')], default='All', max_length=10)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('pregnancy_required', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_eligibility_rules', to='patients.department')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='lab.diagnosis')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
