# Generated by Django 5.2.17 on 2026-09-21 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0059_alter_diagnosisinvestigationmap_options_and_more'),
        ('patients', '0017_ward_alter_patient_guardian_relationship_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationMarkingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marking_date', models.DateField(db_index=True, unique=True, verbose_name='Marking Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SAVED', 'Saved'), ('TRIGGERED', 'Triggered'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('total_male', models.PositiveIntegerField(default=0)),
                ('total_female', models.PositiveIntegerField(default=0)),
                ('total_patients', models.PositiveIntegerField(default=0)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investigation Marking Config',
                'verbose_name_plural': 'Investigation Marking Configs',
                'ordering': ['-marking_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationMarkingDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_name', models.CharField(max_length=150)),
                ('male_count', models.PositiveIntegerField(default=0)),
                ('female_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='lab.investigationmarkingconfig')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.department')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('config', 'department')},
            },
        ),
        migrations.CreateModel(
            name='InvestigationMarkingPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_name', models.CharField(max_length=150)),
                ('patient_id_str', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=150)),
                ('age_display', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('primary_diagnosis_name', models.CharField(blank=True, default='', max_length=255)),
                ('investigations_count', models.PositiveIntegerField(default=0)),
                ('investigations_summary', models.CharField(blank=True, default='', max_length=255)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('completion_due_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_patients', to='lab.investigationmarkingconfig')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('primary_diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.diagnosis')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.servicerequest')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('config', 'patient')},
            },
        ),
    ]
