# Generated by Django 5.2.17 on 2026-09-22 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0060_investigationmarkingconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestinvestigation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ServiceRequestResultAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(max_length=255)),
                ('investigation_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_audits', to='lab.investigationparameter')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_result_modifications', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_audits', to='lab.servicerequest')),
                ('sr_investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_audits', to='lab.servicerequestinvestigation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
