# Generated by Django 5.2.17 on 2026-09-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0061_servicerequestinvestigation_verified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='grp',
            field=models.CharField(choices=[('G', 'Group'), ('I', 'Individual')], default='I', max_length=10, verbose_name='Group Type (Grp)'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='grpi',
            field=models.IntegerField(default=0, verbose_name='Group Index (Grpi)'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='clinical_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Clinical Remarks'),
        ),
        migrations.AddField(
            model_name='servicerequestinvestigation',
            name='doc_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Doc No'),
        ),
    ]
