# Generated by Django 5.2.17 on 2026-09-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0062_investigation_grp_investigation_grpi_and_more'),
        ('patients', '0020_merge_20260923_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to='patients.department', verbose_name='Department'),
        ),
    ]
