# Generated by Django 5.2.17 on 2026-09-23 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0063_alter_investigation_department'),
        ('patients', '0020_merge_20260923_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='investigation_set', to='patients.department', verbose_name='Departments'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to='patients.department', verbose_name='Primary Department'),
        ),
    ]
