# Generated by Django 5.2.17 on 2026-09-30 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0020_merge_20260923_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPrintToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Secure Token')),
                ('print_type', models.CharField(choices=[('OP', 'Out-Patient (OP) Slip'), ('REVIEW', 'Review Visit Slip')], db_index=True, default='OP', max_length=20, verbose_name='Print Slip Type')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='Access Count')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Accessed At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Additional Metadata')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_print_tokens', to='patients.patient', verbose_name='Patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_print_tokens', to='patients.patientvisit', verbose_name='Specific Visit')),
            ],
            options={
                'verbose_name': 'Public Print Token',
                'verbose_name_plural': 'Public Print Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('print_type', models.CharField(default='OP', max_length=20)),
                ('printer_name', models.CharField(default='', max_length=100)),
                ('printer_type', models.CharField(default='generic', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent to Printer Spooler'), ('PRINTED', 'Successfully Printed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('raw_payload', models.TextField(blank=True, verbose_name='PRN / Raw Payload')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='patients.patient')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='printing.publicprinttoken')),
            ],
            options={
                'verbose_name': 'Print Job',
                'verbose_name_plural': 'Print Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='publicprinttoken',
            index=models.Index(fields=['token', 'is_active'], name='printing_pu_token_ee3caa_idx'),
        ),
        migrations.AddIndex(
            model_name='publicprinttoken',
            index=models.Index(fields=['patient', 'print_type', 'is_active'], name='printing_pu_patient_615e45_idx'),
        ),
    ]
