# Generated by Django 5.2.17 on 2026-09-25 09:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0020_merge_20260923_1227'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(max_length=50, unique=True, verbose_name='Request No')),
                ('bed_room', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bed / Room No')),
                ('admission_type', models.CharField(choices=[('General Admission', 'General Admission'), ('Emergency / Casualty', 'Emergency / Casualty'), ('Day Care', 'Day Care'), ('ICU / Critical Care', 'ICU / Critical Care'), ('Maternity / Delivery', 'Maternity / Delivery'), ('Surgical Admission', 'Surgical Admission'), ('Insurance / Corporate', 'Insurance / Corporate'), ('Other', 'Other')], default='General Admission', max_length=50, verbose_name='Admission Type')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Request Date & Time')),
                ('reason_remarks', models.TextField(blank=True, null=True, verbose_name='Reason / Clinical Remarks')),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], default='Normal', max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Admitted', 'Admitted')], default='Pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed Date & Time')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='Review Notes')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_requests', to='patients.department', verbose_name='Department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requests', to='patients.patient', verbose_name='Patient')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_admissions', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admissions', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('unit_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_requests', to='patients.departmentunit', verbose_name='Unit / Doctor')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_requests', to='patients.ward', verbose_name='Requested Ward')),
            ],
            options={
                'verbose_name': 'Admission Request',
                'verbose_name_plural': 'Admission Requests',
                'ordering': ['-request_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CRMEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller_mobile', models.CharField(max_length=20, verbose_name='Caller Mobile No')),
                ('caller_name', models.CharField(max_length=150, verbose_name='Caller Name')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Street')),
                ('area_village', models.CharField(blank=True, max_length=150, null=True, verbose_name='Area / Village')),
                ('city', models.CharField(default='Karaikal', max_length=100, verbose_name='City')),
                ('pincode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pincode')),
                ('alternate_contact', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alternate Contact')),
                ('category', models.CharField(choices=[('General Enquiry', 'General Enquiry'), ('Appointment', 'Appointment'), ('Doctor Enquiry', 'Doctor Enquiry'), ('Department Enquiry', 'Department Enquiry'), ('Admission Enquiry', 'Admission Enquiry'), ('Billing Enquiry', 'Billing Enquiry'), ('Laboratory Enquiry', 'Laboratory Enquiry'), ('Pharmacy Enquiry', 'Pharmacy Enquiry'), ('Insurance', 'Insurance'), ('Complaint', 'Complaint'), ('Feedback', 'Feedback'), ('Other', 'Other')], default='General Enquiry', max_length=50, verbose_name='Category')),
                ('enquiry_about', models.TextField(verbose_name='Enquiry About')),
                ('caller_source', models.CharField(choices=[('Phone Call', 'Phone Call'), ('Walk-in', 'Walk-in'), ('Website Enquiry', 'Website Enquiry'), ('Email', 'Email'), ('Referral', 'Referral'), ('Other', 'Other')], default='Phone Call', max_length=50, verbose_name='Caller Type / Source')),
                ('assign_to', models.CharField(max_length=150, verbose_name='Assign To')),
                ('assign_contact', models.CharField(blank=True, max_length=30, null=True, verbose_name='Assign Contact No')),
                ('followup_date', models.DateField(blank=True, null=True, verbose_name='Follow-up Date')),
                ('call_received_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Call Received By')),
                ('call_date', models.DateField(default=django.utils.timezone.now, verbose_name='Call Received Date')),
                ('call_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Call Received Time')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Follow-up', 'Follow-up'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_enquiries', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'CRM Enquiry',
                'verbose_name_plural': 'CRM Enquiries',
                'ordering': ['-id'],
            },
        ),
    ]
