# Generated by Django 5.2.17 on 2026-08-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Department Manager'), ('STAFF', 'Staff Member'), ('AUDITOR', 'Auditor')], max_length=20, unique=True)),
                ('menu_permissions', models.JSONField(default=dict)),
            ],
        ),
    ]
