# Generated by Django 5.2.17 on 2026-08-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rolemenupermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique uppercase role key e.g. DOCTOR, RECEPTIONIST', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Human-readable role title e.g. Doctor / Specialist', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#0284c7', max_length=20)),
                ('badge_class', models.CharField(default='badge-blue', max_length=50)),
                ('icon', models.CharField(default='bi-person-badge-fill', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='rolemenupermission',
            name='role',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
