# Generated by Django 5.2.17 on 2026-08-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customrole_alter_rolemenupermission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='STAFF', help_text='Role within the ERP system', max_length=50),
        ),
    ]
