# Generated by Django 5.2.17 on 2026-09-24 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier key (e.g. patients, lab, custom_mod)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display title in top navbar', max_length=100)),
                ('icon', models.CharField(default='bi-folder2', help_text='Bootstrap icon class', max_length=50)),
                ('url_path', models.CharField(default='#', help_text='Default URL or target link', max_length=255)),
                ('color', models.CharField(default='#0284c7', help_text='Hex color or badge accent', max_length=20)),
                ('badge', models.CharField(blank=True, help_text='Short category badge', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Nav Module',
                'verbose_name_plural': 'Nav Modules',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavSubmodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Permission / lookup key', max_length=60, unique=True)),
                ('name', models.CharField(help_text='Submodule link title', max_length=100)),
                ('icon', models.CharField(default='bi-dot', help_text='Bootstrap icon class', max_length=50)),
                ('url_path', models.CharField(default='#', help_text='Target URL or pattern', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='users.navmodule')),
            ],
            options={
                'verbose_name': 'Nav Submodule',
                'verbose_name_plural': 'Nav Submodules',
                'ordering': ['order', 'id'],
            },
        ),
    ]
