# Generated by Django 5.2.17 on 2026-09-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_navmodule_navsubmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal identifier code (e.g. front_desk, consultant)', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL slug for login portal (e.g. front-desk)', max_length=60, unique=True)),
                ('name', models.CharField(help_text='Department display title on landing card', max_length=100)),
                ('icon', models.CharField(default='bi-hospital', help_text='Bootstrap icon class (e.g. bi-person-workspace)', max_length=50)),
                ('color_bg', models.CharField(default='#e0f2fe', help_text='Icon badge background hex color', max_length=20)),
                ('color_icon', models.CharField(default='#0284c7', help_text='Icon foreground hex color', max_length=20)),
                ('badge', models.CharField(blank=True, help_text='Subtitle or category badge on the card', max_length=80, null=True)),
                ('dashboard_url', models.CharField(default='/dashboard/', help_text='Destination dashboard URL after successful login', max_length=255)),
                ('landing_module', models.CharField(blank=True, help_text='Permission module code', max_length=60, null=True)),
                ('allowed_prefixes', models.JSONField(blank=True, default=list, help_text='List of URL path prefixes allowed for this department')),
                ('aliases', models.JSONField(blank=True, default=list, help_text='List of staff user department keywords matching this department')),
                ('description', models.TextField(blank=True, help_text='Department duties, scope and notes', null=True)),
                ('order', models.PositiveIntegerField(default=10, help_text='Sort order on landing grid')),
                ('is_active', models.BooleanField(default=True, help_text='Whether visible on the landing page')),
                ('is_system', models.BooleanField(default=False, help_text='System-protected default department')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Landing Department',
                'verbose_name_plural': 'Landing Departments',
                'ordering': ['order', 'id'],
            },
        ),
    ]
