# Generated by Django 5.2.17 on 2026-09-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_landingdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingdepartment',
            name='nav_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Department-specific Top Navigation Bar modules and submodules access mapping'),
        ),
    ]
