# Generated by Django 5.2.17 on 2026-10-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_landingdepartment_nav_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text="Assigned department(s) (comma-separated or 'All Departments')", max_length=500, null=True),
        ),
    ]
