# Generated by Django 5.2.17 on 2026-10-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_landingdepartment_nav_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, default='vmmc-main', help_text='User interface theme preference', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_font',
            field=models.CharField(blank=True, default='Outfit', help_text='User interface font family preference', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text="Assigned department(s) (comma-separated or 'All Departments')", max_length=500, null=True),
        ),
    ]
