# Generated by Django 5.2.17 on 2026-10-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_theme_user_theme_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_motion',
            field=models.CharField(blank=True, default='medium', help_text='User interface motion level: off, low, medium, high', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, default='vmmc-main', help_text='User interface theme preference', max_length=100),
        ),
    ]
