# Generated by Django 5.2.17 on 2026-08-21 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Department Code')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Company Code')),
                ('name', models.CharField(max_length=150, verbose_name='Company / Scheme Name')),
                ('category', models.CharField(choices=[('INDIVIDUAL', 'Individual / Self Pay'), ('STAFF', 'Internal Staff / VMMC'), ('GOVT', 'Government Scheme (CGHS / ESI)'), ('INSURANCE', 'Insurance / TPA'), ('CORPORATE', 'Corporate Tie-up')], default='INDIVIDUAL', max_length=30)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount (%)')),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'verbose_name_plural': 'Patient Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_name', models.CharField(max_length=150, verbose_name='Unit / Doctor Name')),
                ('head_doctor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Head Doctor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='patients.department')),
            ],
            options={
                'ordering': ['unit_name'],
                'unique_together': {('department', 'unit_name')},
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ipno', models.CharField(blank=True, max_length=50, null=True, verbose_name='IPNO')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Master', 'Master'), ('Dr', 'Dr'), ('Baby', 'Baby')], default='Mr', max_length=10)),
                ('name', models.CharField(max_length=150, verbose_name='Patient Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('age_years', models.PositiveIntegerField(default=0, verbose_name='Age (Years)')),
                ('age_months', models.PositiveIntegerField(default=0, verbose_name='Age (Months)')),
                ('age_days', models.PositiveIntegerField(default=0, verbose_name='Age (Days)')),
                ('aadhar_card', models.CharField(blank=True, max_length=20, null=True, verbose_name='AAdhar Card')),
                ('visit_through', models.CharField(choices=[('OP', 'Out-Patient (OP)'), ('IP', 'In-Patient (IP)')], default='OP', max_length=10)),
                ('category', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('CASUALTY', 'Casualty'), ('EMERGENCY', 'Emergency'), ('RE_CONSULTATION', 'Re-Consultation')], default='CONSULTATION', max_length=50)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('religion', models.CharField(blank=True, max_length=30, null=True)),
                ('guardian_relationship', models.CharField(choices=[('S/O', 'S/O (Son of)'), ('D/O', 'D/O (Daughter of)'), ('W/O', 'W/O (Wife of)'), ('C/O', 'C/O (Care of)')], default='S/O', max_length=10)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(default='INDIVIDUAL', max_length=100)),
                ('abha_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ABHAID')),
                ('ofc_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='OFC Code')),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('village_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Village / Area')),
                ('country', models.CharField(default='India', max_length=50)),
                ('state', models.CharField(default='Puducherry', max_length=50)),
                ('city', models.CharField(default='Karaikal', max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_no', models.CharField(max_length=20, verbose_name='Mobile No (without 91)')),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('complaint', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('income', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(default='GENERAL MEDICINE', max_length=100)),
                ('unit_doctor', models.CharField(default='HOD-GENERAL MEDICINE-V', max_length=100, verbose_name='Unit / Doctor')),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN No')),
                ('department_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.department')),
                ('unit_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.departmentunit')),
                ('patient_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.patientcompany')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
