# Generated by Django 5.2.17 on 2026-08-23 12:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_no', models.PositiveIntegerField(verbose_name='Visit No')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Visit Date & Time')),
                ('department', models.CharField(default='GENERAL MEDICINE', max_length=100)),
                ('unit_doctor', models.CharField(default='HOD-GENERAL MEDICINE-V', max_length=100, verbose_name='Unit / Doctor')),
                ('visit_type', models.CharField(choices=[('OP', 'Out-Patient (OP)'), ('IP', 'In-Patient (IP)')], default='OP', max_length=20)),
                ('category', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('CASUALTY', 'Casualty'), ('EMERGENCY', 'Emergency'), ('RE_CONSULTATION', 'Re-Consultation')], default='RE_CONSULTATION', max_length=50)),
                ('ipno', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP Number')),
                ('ward', models.CharField(blank=True, max_length=50, null=True)),
                ('bed', models.CharField(blank=True, max_length=50, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='Date of Discharge')),
                ('ref_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ref No')),
                ('ref_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referred By')),
                ('ref_date', models.DateField(blank=True, null=True, verbose_name='Ref Date')),
                ('reg_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Registration Fees')),
                ('coll_status', models.CharField(default='Paid', max_length=20, verbose_name='Collection Status')),
                ('clinical_notes', models.TextField(blank=True, null=True, verbose_name='Clinical Notes / Diagnosis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('department_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='patients.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
                ('unit_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='patients.departmentunit')),
            ],
            options={
                'ordering': ['-visit_no'],
                'unique_together': {('patient', 'visit_no')},
            },
        ),
    ]
