# Generated by Django 5.2.17 on 2026-08-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='centre',
            field=models.CharField(choices=[('VMMCH', 'VMMCH'), ('CAMP', 'Camp'), ('RURAL', 'Rural'), ('URBAN', 'Urban')], default='VMMCH', max_length=50, verbose_name='Centre'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='centre',
            field=models.CharField(choices=[('VMMCH', 'VMMCH'), ('CAMP', 'Camp'), ('RURAL', 'Rural'), ('URBAN', 'Urban')], default='VMMCH', max_length=50, verbose_name='Centre'),
        ),
    ]
