# Generated by Django 5.2.17 on 2026-08-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_centre_patientvisit_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='guardian_relationship',
            field=models.CharField(choices=[('-', '-'), ('S/O', 'S/O (Son of)'), ('D/O', 'D/O (Daughter of)'), ('W/O', 'W/O (Wife of)'), ('C/O', 'C/O (Care of)'), ('H/O', 'H/O (Husband of)'), ('F/O', 'F/O (Father of)'), ('M/O', 'M/O (Mother of)')], default='-', max_length=10),
        ),
    ]
