# Generated by Django 5.2.17 on 2026-08-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_guardian_relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentunit',
            options={'ordering': ['department', 'display_order', 'unit_name']},
        ),
        migrations.AddField(
            model_name='departmentunit',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Unit/Doctor Code'),
        ),
        migrations.AddField(
            model_name='departmentunit',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='departmentunit',
            name='unit_type',
            field=models.CharField(choices=[('HOD', 'HOD'), ('Unit', 'Unit'), ('Doctor', 'Doctor'), ('Consultant', 'Consultant'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Type'),
        ),
    ]
