# Generated by Django 5.2.17 on 2026-08-25 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_departmentunit_options_departmentunit_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Alternate Phone'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='patient',
            name='op_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='OP Number'),
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Registration Date'),
        ),
        migrations.CreateModel(
            name='PatientImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('total_records', models.IntegerField(default=0)),
                ('imported', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
