# Generated by Django 5.2.17 on 2026-08-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_alternate_phone_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Guardian Phone'),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_title',
            field=models.CharField(choices=[('-', '-'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Master', 'Master'), ('Dr', 'Dr'), ('Baby', 'Baby')], default='-', max_length=10),
        ),
    ]
