# Generated by Django 5.2.17 on 2026-08-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patient_guardian_phone_patient_guardian_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientimporthistory',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='patient_imports/'),
        ),
    ]
