# Generated by Django 5.2.17 on 2026-08-29 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0034_autotriggerlog_scheduled_at'),
        ('patients', '0010_patientimporthistory_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='auto_trigger_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_patients', to='lab.autotriggerhistory', verbose_name='Auto Trigger Run'),
        ),
        migrations.AddField(
            model_name='patient',
            name='auto_trigger_stage',
            field=models.CharField(blank=True, default='STAGE 1 - PATIENT CREATION', max_length=100, null=True, verbose_name='Auto Trigger Stage'),
        ),
        migrations.AddField(
            model_name='patient',
            name='automation_scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Scheduled Creation Date & Time'),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_source',
            field=models.CharField(choices=[('O', 'Normal Entry'), ('D', 'Auto Trigger Entry')], db_index=True, default='O', max_length=1, verbose_name='Entry Type / Source'),
        ),
        migrations.AddField(
            model_name='patient',
            name='source_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_triggered_copies', to='patients.patient', verbose_name='Source Patient Reference'),
        ),
    ]
