# Generated by Django 5.2.17 on 2026-08-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patient_auto_trigger_run_patient_auto_trigger_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('O', 'Normal Entry'), ('D', 'Auto Trigger Entry')], db_index=True, default='O', max_length=1, verbose_name='Patient Type'),
        ),
    ]
