# Generated by Django 5.2.17 on 2026-09-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_patient_patient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='visit_through',
            field=models.CharField(choices=[('OP', 'Out-Patient (OP)'), ('IP', 'In-Patient (IP)'), ('REVIEW', 'Review')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='visit_type',
            field=models.CharField(choices=[('OP', 'Out-Patient (OP)'), ('IP', 'In-Patient (IP)'), ('REVIEW', 'Review')], default='OP', max_length=20),
        ),
    ]
