# Generated by Django 5.2.17 on 2026-09-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_patient_visit_through_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='discharge_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Discharge Summary / Advice'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='discharge_type',
            field=models.CharField(blank=True, default='Normal / Improved', max_length=50, null=True, verbose_name='Discharge Type / Status'),
        ),
    ]
