# Generated by Django 5.2.17 on 2026-09-13 08:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_patientvisit_discharge_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_request_number', models.CharField(max_length=50, unique=True, verbose_name='Transfer Request ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('transfer_reason', models.TextField(verbose_name='Transfer Reason / Notes')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Requested Date & Time')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed Date & Time')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='Review / Rejection Notes')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled Date & Time')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Cancellation Reason')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_transfers', to='patients.patientvisit', verbose_name='Active Admission')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_branch_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By')),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_branch_transfers', to='patients.department', verbose_name='Current Department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_transfers', to='patients.patient', verbose_name='Patient')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_branch_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_branch_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_branch_transfers', to='patients.department', verbose_name='Requested Department')),
                ('to_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_unit_transfers', to='patients.departmentunit', verbose_name='Destination Unit / Doctor')),
            ],
            options={
                'verbose_name': 'Branch Transfer Request',
                'verbose_name_plural': 'Branch Transfer Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
