# Generated by Django 5.2.17 on 2026-09-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_branchtransferrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Mobile No (without 91)'),
        ),
    ]
