# Generated by Django 5.2.17 on 2026-09-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_alter_patient_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ward Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Ward Code')),
                ('ward_type', models.CharField(choices=[('GENERAL', 'General Ward'), ('SPECIAL', 'Special Ward'), ('SEMI_SPECIAL', 'Semi-Special Ward'), ('ICU', 'ICU / Critical Care'), ('EMERGENCY', 'Emergency / Casualty'), ('POST_OP', 'Post-Operative Ward'), ('MATERNITY', 'Maternity / OG Ward'), ('PAEDIATRIC', 'Paediatric Ward'), ('ISOLATION', 'Isolation Ward'), ('DAY_CARE', 'Day Care Ward'), ('OTHER', 'Other')], default='GENERAL', max_length=30, verbose_name='Ward Type')),
                ('total_beds', models.PositiveIntegerField(default=10, verbose_name='Total Beds')),
                ('floor_building', models.CharField(blank=True, max_length=100, null=True, verbose_name='Building / Floor / Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'verbose_name': 'Hospital Ward',
                'verbose_name_plural': 'Hospital Wards',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='guardian_relationship',
            field=models.CharField(choices=[('-', '-'), ('S/O', 'S/O (Son of)'), ('D/O', 'D/O (Daughter of)'), ('W/O', 'W/O (Wife of)'), ('C/O', 'C/O (Care of)'), ('H/O', 'H/O (Husband of)'), ('F/O', 'F/O (Father of)'), ('M/O', 'M/O (Mother of)'), ('G/O', 'G/O (Guardian of)')], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='guardian_title',
            field=models.CharField(choices=[('-', '-'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Master', 'Master'), ('Dr', 'Dr'), ('Baby', 'Baby')], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='title',
            field=models.CharField(choices=[('-', '-'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Master', 'Master'), ('Dr', 'Dr'), ('Baby', 'Baby')], default='-', max_length=10),
        ),
    ]
