# Generated by Django 5.2.17 on 2026-09-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_alter_patient_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='guardian_relationship',
            field=models.CharField(choices=[('-', '-'), ('S/O', 'S/O (Son of)'), ('D/O', 'D/O (Daughter of)'), ('W/O', 'W/O (Wife of)'), ('C/O', 'C/O (Care of)'), ('H/O', 'H/O (Husband of)'), ('F/O', 'F/O (Father of)'), ('M/O', 'M/O (Mother of)'), ('G/O', 'G/O (Guardian of)')], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='guardian_title',
            field=models.CharField(choices=[('-', '-'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Master', 'Master'), ('Dr', 'Dr'), ('Baby', 'Baby')], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='title',
            field=models.CharField(choices=[('-', '-'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Master', 'Master'), ('Dr', 'Dr'), ('Baby', 'Baby')], default='-', max_length=10),
        ),
    ]
