# Generated by Django 5.2.17 on 2026-09-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_ward_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='gender_category',
            field=models.CharField(choices=[('MALE', 'Male Patients Only'), ('FEMALE', 'Female Patients Only'), ('UNISEX', 'Both / Unisex (Male & Female)'), ('PAEDIATRIC', 'Paediatric (Children)')], default='UNISEX', max_length=20, verbose_name='Patient Gender / Category'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_type',
            field=models.CharField(choices=[('GENERAL', 'General Ward'), ('MALE_GENERAL', 'Male General Ward'), ('FEMALE_GENERAL', 'Female General Ward'), ('MALE_MEDICAL', 'Male Medical Ward'), ('FEMALE_MEDICAL', 'Female Medical Ward'), ('MALE_SURGICAL', 'Male Surgical Ward'), ('FEMALE_SURGICAL', 'Female Surgical Ward'), ('SPECIAL', 'Special Ward'), ('SEMI_SPECIAL', 'Semi-Special Ward'), ('ICU', 'ICU / Critical Care'), ('EMERGENCY', 'Emergency / Casualty'), ('POST_OP', 'Post-Operative Ward'), ('MATERNITY', 'Maternity / OG Ward (Female)'), ('PAEDIATRIC', 'Paediatric Ward (Child)'), ('ISOLATION', 'Isolation Ward'), ('DAY_CARE', 'Day Care Ward'), ('OTHER', 'Other')], default='GENERAL', max_length=30, verbose_name='Ward Type'),
        ),
    ]
