# Generated by Django 5.2.17 on 2026-09-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_alter_patient_guardian_relationship_and_more'),
        ('patients', '0019_ward_gender_category_alter_ward_ward_type'),
    ]

    operations = [
    ]
