# Generated by Django 5.2.17 on 2026-10-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_merge_20260923_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='category',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('CASUALTY', 'Casualty'), ('EMERGENCY', 'Emergency'), ('RE_CONSULTATION', 'Re-Consultation'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Red', 'Red'), ('Black', 'Black')], default='CONSULTATION', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='guardian_relationship',
            field=models.CharField(choices=[('-', '-'), ('S/O', 'S/O (Son of)'), ('D/O', 'D/O (Daughter of)'), ('W/O', 'W/O (Wife of)'), ('C/O', 'C/O (Care of)'), ('H/O', 'H/O (Husband of)'), ('F/O', 'F/O (Father of)'), ('M/O', 'M/O (Mother of)'), ('G/O', 'G/O (Guardian of)'), ('Relative', 'Relative'), ('Neighbour', 'Neighbour'), ('Friend', 'Friend'), ('Police', 'Police'), ('Self', 'Self'), ('Unknown', 'Unknown')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='category',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('CASUALTY', 'Casualty'), ('EMERGENCY', 'Emergency'), ('RE_CONSULTATION', 'Re-Consultation'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Red', 'Red'), ('Black', 'Black')], default='RE_CONSULTATION', max_length=50),
        ),
    ]
