import os

with open("apps/lab/views.py", "a") as f:
    f.write("\n\n@csrf_exempt\n@login_required\ndef api_investigation_parameter_mapping_save(request):\n")
    f.write("    if request.method == 'POST':\n")
    f.write("        try:\n")
    f.write("            import json\n")
    f.write("            data = json.loads(request.body)\n")
    f.write("            mapping_id = data.get('id')\n")
    f.write("            investigation_id = data.get('investigation_id')\n")
    f.write("            parameter_id = data.get('parameter_id')\n")
    f.write("            is_active = data.get('is_active', True)\n")
    f.write("            \n")
    f.write("            if not investigation_id or not parameter_id:\n")
    f.write("                return JsonResponse({'status': 'error', 'message': 'Investigation and Parameter are required.'})\n")
    f.write("                \n")
    f.write("            from .models import InvestigationParameter\n")
    f.write("            duplicate = InvestigationParameter.objects.filter(investigation_id=investigation_id, parameter_id=parameter_id)\n")
    f.write("            if mapping_id:\n")
    f.write("                duplicate = duplicate.exclude(id=mapping_id)\n")
    f.write("            if duplicate.exists():\n")
    f.write("                return JsonResponse({'status': 'error', 'message': 'This mapping already exists.'})\n")
    f.write("                \n")
    f.write("            if mapping_id:\n")
    f.write("                mapping = InvestigationParameter.objects.get(id=mapping_id)\n")
    f.write("                mapping.investigation_id = investigation_id\n")
    f.write("                mapping.parameter_id = parameter_id\n")
    f.write("                mapping.is_active = is_active\n")
    f.write("                mapping.save()\n")
    f.write("                msg = 'Mapping updated successfully.'\n")
    f.write("            else:\n")
    f.write("                mapping = InvestigationParameter.objects.create(\n")
    f.write("                    investigation_id=investigation_id,\n")
    f.write("                    parameter_id=parameter_id,\n")
    f.write("                    is_active=is_active\n")
    f.write("                )\n")
    f.write("                msg = 'Mapping created successfully.'\n")
    f.write("                \n")
    f.write("            return JsonResponse({\n")
    f.write("                'status': 'success',\n")
    f.write("                'message': msg,\n")
    f.write("                'data': {\n")
    f.write("                    'id': mapping.id,\n")
    f.write("                    'investigation_id': mapping.investigation_id,\n")
    f.write("                    'parameter_id': mapping.parameter_id,\n")
    f.write("                    'is_active': mapping.is_active\n")
    f.write("                }\n")
    f.write("            })\n")
    f.write("        except Exception as e:\n")
    f.write("            return JsonResponse({'status': 'error', 'message': str(e)})\n")
    f.write("    return JsonResponse({'status': 'error', 'message': 'Invalid request method.'})\n")

    f.write("\n\n@csrf_exempt\n@login_required\ndef api_investigation_parameter_mapping_delete(request, pk):\n")
    f.write("    if request.method == 'POST':\n")
    f.write("        try:\n")
    f.write("            from .models import InvestigationParameter\n")
    f.write("            mapping = InvestigationParameter.objects.get(id=pk)\n")
    f.write("            mapping.delete()\n")
    f.write("            return JsonResponse({'status': 'success', 'message': 'Mapping deleted successfully.'})\n")
    f.write("        except Exception as e:\n")
    f.write("            return JsonResponse({'status': 'error', 'message': str(e)})\n")
    f.write("    return JsonResponse({'status': 'error', 'message': 'Invalid request method.'})\n")


with open("apps/lab/urls.py", "r") as f:
    content = f.read()

content = content.replace("urlpatterns = [", "urlpatterns = [\n    path('api/investigation-parameter-mapping/save/', views.api_investigation_parameter_mapping_save, name='api_investigation_parameter_mapping_save'),\n    path('api/investigation-parameter-mapping/<int:pk>/delete/', views.api_investigation_parameter_mapping_delete, name='api_investigation_parameter_mapping_delete'),")

with open("apps/lab/urls.py", "w") as f:
    f.write(content)

