import os

with open("apps/lab/views.py", "a") as f:
    f.write("\n\n@csrf_exempt\n@login_required\ndef api_referencerange_save(request):\n")
    f.write("    if request.method == 'POST':\n")
    f.write("        try:\n")
    f.write("            import json\n")
    f.write("            data = json.loads(request.body)\n")
    f.write("            rr_id = data.get('id')\n")
    f.write("            investigation_parameter_id = data.get('investigation_parameter_id')\n")
    f.write("            age_group_id = data.get('age_group_id')\n")
    f.write("            min_val = data.get('min_value')\n")
    f.write("            max_val = data.get('max_value')\n")
    f.write("            normal_val = data.get('normal_value')\n")
    f.write("            unit = data.get('unit')\n")
    f.write("            remarks = data.get('remarks')\n")
    f.write("            is_active = data.get('is_active', True)\n")
    f.write("            \n")
    f.write("            if not investigation_parameter_id or not age_group_id:\n")
    f.write("                return JsonResponse({'status': 'error', 'message': 'Parameter and Age Group are required.'})\n")
    f.write("                \n")
    f.write("            from .models import ParameterReferenceRange\n")
    f.write("            duplicate = ParameterReferenceRange.objects.filter(investigation_parameter_id=investigation_parameter_id, age_group_id=age_group_id)\n")
    f.write("            if rr_id:\n")
    f.write("                duplicate = duplicate.exclude(id=rr_id)\n")
    f.write("            if duplicate.exists():\n")
    f.write("                return JsonResponse({'status': 'error', 'message': 'Reference Range for this Parameter and Age Group already exists.'})\n")
    f.write("                \n")
    f.write("            if rr_id:\n")
    f.write("                rr = ParameterReferenceRange.objects.get(id=rr_id)\n")
    f.write("                rr.investigation_parameter_id = investigation_parameter_id\n")
    f.write("                rr.age_group_id = age_group_id\n")
    f.write("                rr.min_value = min_val if min_val else None\n")
    f.write("                rr.max_value = max_val if max_val else None\n")
    f.write("                rr.normal_value = normal_val\n")
    f.write("                rr.unit = unit\n")
    f.write("                rr.remarks = remarks\n")
    f.write("                rr.is_active = is_active\n")
    f.write("                rr.save()\n")
    f.write("                msg = 'Reference Range updated successfully.'\n")
    f.write("            else:\n")
    f.write("                rr = ParameterReferenceRange.objects.create(\n")
    f.write("                    investigation_parameter_id=investigation_parameter_id,\n")
    f.write("                    age_group_id=age_group_id,\n")
    f.write("                    min_value=min_val if min_val else None,\n")
    f.write("                    max_value=max_val if max_val else None,\n")
    f.write("                    normal_value=normal_val,\n")
    f.write("                    unit=unit,\n")
    f.write("                    remarks=remarks,\n")
    f.write("                    is_active=is_active\n")
    f.write("                )\n")
    f.write("                msg = 'Reference Range created successfully.'\n")
    f.write("                \n")
    f.write("            return JsonResponse({\n")
    f.write("                'status': 'success',\n")
    f.write("                'message': msg,\n")
    f.write("                'data': {\n")
    f.write("                    'id': rr.id,\n")
    f.write("                    'investigation_parameter_id': rr.investigation_parameter_id,\n")
    f.write("                    'age_group_id': rr.age_group_id,\n")
    f.write("                    'min_value': rr.min_value,\n")
    f.write("                    'max_value': rr.max_value,\n")
    f.write("                    'normal_value': rr.normal_value,\n")
    f.write("                    'unit': rr.unit,\n")
    f.write("                    'remarks': rr.remarks,\n")
    f.write("                    'is_active': rr.is_active\n")
    f.write("                }\n")
    f.write("            })\n")
    f.write("        except Exception as e:\n")
    f.write("            return JsonResponse({'status': 'error', 'message': str(e)})\n")
    f.write("    return JsonResponse({'status': 'error', 'message': 'Invalid request method.'})\n")

    f.write("\n\n@csrf_exempt\n@login_required\ndef api_referencerange_delete(request, pk):\n")
    f.write("    if request.method == 'POST':\n")
    f.write("        try:\n")
    f.write("            from .models import ParameterReferenceRange\n")
    f.write("            rr = ParameterReferenceRange.objects.get(id=pk)\n")
    f.write("            rr.delete()\n")
    f.write("            return JsonResponse({'status': 'success', 'message': 'Reference Range deleted successfully.'})\n")
    f.write("        except Exception as e:\n")
    f.write("            return JsonResponse({'status': 'error', 'message': str(e)})\n")
    f.write("    return JsonResponse({'status': 'error', 'message': 'Invalid request method.'})\n")


with open("apps/lab/urls.py", "r") as f:
    content = f.read()

content = content.replace("urlpatterns = [", "urlpatterns = [\n    path('api/reference-range/save/', views.api_referencerange_save, name='api_referencerange_save'),\n    path('api/reference-range/<int:pk>/delete/', views.api_referencerange_delete, name='api_referencerange_delete'),")

with open("apps/lab/urls.py", "w") as f:
    f.write(content)
